CREATE OR REPLACE DATABASE DMS_CDC_DB;
CREATE OR REPLACE SCHEMA DMS_CDC_DB.RAW;
CREATE OR REPLACE SCHEMA DMS_CDC_DB.CURATED;

CREATE OR REPLACE FILE FORMAT DMS_CDC_DB.RAW.PARQUET_FF TYPE = PARQUET;

CREATE OR REPLACE STAGE DMS_CDC_DB.RAW.DMS_S3_STAGE
  URL = 's3://dms-s3-parquet-target-v1/public/'
  STORAGE_INTEGRATION = s3_dms_int
  FILE_FORMAT = DMS_CDC_DB.RAW.PARQUET_FF;

-- LIST @DMS_CDC_DB.RAW.DMS_S3_STAGE;